version: '3'

services:

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER:${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD:${MINIO_ROOT_PASSWORD}
    command: "server /data --console-address ':9001'"
    env_file: '.env'

volumes:
  mongo_data:
  minio_data:
